(function (l, a, y, e, r, s, _) {
  l['DoofinderAppsObject'] = r; l[r] = l[r] || function () { (l[r].q = l[r].q || []).push(arguments) };
  s = a.createElement(y); s.async = 1; s.src = e; _ = a.getElementsByTagName(y)[0]; _.parentNode.insertBefore(s, _)
})(window, document, 'script', 'https://cdn.doofinder.com/apps/loader/2.x/loader.min.js', 'doofinderApp');

doofinderApp("config", "store", "01cc0dde-c3ff-49c1-b465-37aa2c40c86a")
doofinderApp("config", "zone", "eu1")

doofinderApp("config", "settings",
[{"vsn":"1.0","apps":[{"name":"layer","type":"search","options":{"trigger":"#seek, #seekfixedleft","zone":"eu1","chat":{"bubble_messages":{"a5271756a99534c5e04f33f3f35edf93":"¿Necesitas ayuda? ¡Cuenta con nuestro asistente!"},"bubble_settings":{"desktop":{"bubble_enabled":true,"bubble_message_enabled":false,"bubble_background_color":"#ff9316","bubble_position":"bottom_right","bubble_vertical_offset":75,"bubble_icon":null},"mobile":{"bubble_enabled":false,"bubble_message_enabled":true,"bubble_background_color":"#ff9316","bubble_position":"bottom_right","bubble_vertical_offset":0,"bubble_icon":null}}},"url_hash":true},"overrides":{"autoload":{"desktop":null,"mobile":null},"layout":"AIFullscreen","custom_css":{"desktop":[".dfd-card-outofstock {\n    margin-top: 15px !important;\n}\n\n.dfd-chat-bubble svg g {\n  filter: none!important;\n}\n"],"mobile":[".dfd-card-outofstock {\n    margin-top: 15px !important;\n}"]},"custom_properties":{"desktop":["--df-accent-primary: #ff8911;\n--df-accent-primary-hover: #F77C00;\n--df-accent-primary-active: #DD6F00;\n--df-card-flag-discount-background: #ff8911;"],"mobile":["--df-accent-primary: #ff8911;\n--df-accent-primary-hover: #F77C00;\n--df-accent-primary-active: #DD6F00;\n--df-card-flag-discount-background: #ff8911;"]},"search_query_retention":true}}],"settings":{"defaults":{"currency":"EUR","language":"es","hashid":"a5271756a99534c5e04f33f3f35edf93"},"account_code":"aa7107f3fc7fd9f5ff97004c7890b8","search_engines":{"es":{"EUR":"a5271756a99534c5e04f33f3f35edf93"}},"checkout_css_selector":".basis-2/3","checkout_cart_item_selector":".flex.gap-8","checkout_item_title_selector":"h4.font-semibold > a","checkout_item_price_selector":"div.hidden.lg\\:block > p.font-bold","checkout_item_quantity_selector":"input.input.input-bordered.w-16.input-sm.text-center.rounded-md","checkout_summary_urls":[{"value":"/carro/","match_type":"contains"},{"value":"/confirmation","match_type":"contains"},{"value":"https://www.coolmod.com/pedido/#/confirmation","match_type":"equals"}],"checkout_confirmation_urls":[{"value":"/tramitar-pedido/","match_type":"contains"},{"value":"https://www.coolmod.com/tramitar-pedido/","match_type":"contains"}],"sales_api_integration":false,"require_cookies_consent":true,"page_type_mappings":[{"id":36327,"type":"home","match_conditions":[]},{"id":86862,"type":"product_pages","match_conditions":[]},{"id":137397,"type":"category_pages","match_conditions":[]},{"id":187932,"type":"shopping_cart","match_conditions":[]}],"register_visits":true,"register_checkouts":true,"ga4_integration":true,"integrations_list":[],"platform_integration_type":"other","user_history_enabled":false}}])